data_path: "out/ALL_features_cleaned.parquet"
out_dir: "out/modeling_personalized"

id_col: "ID"
time_col: "Time"
target: "Glucose"
drop_cols: ["Time"]

# RF feature selection
fs_threshold: 0.005
rf_n_estimators: 1000
rf_random_state: 42

base_params:
  max_depth: 6
  n_estimators: 100
  learning_rate: 0.1
  min_child_weight: 1.0
  subsample: 1.0
  colsample_bytree: 1.0
  reg_lambda: 1.0
  tree_method: "hist"
  n_jobs: 8
  random_state: 42
base_early_stopping_rounds: null
