data_path: "/Users/bmb47/Documents/Research/code/glucose-prediction/out/ALL_features_cleaned.parquet"
out_dir: "/Users/bmb47/Documents/Research/code/glucose-prediction/out/modeling_population"

id_col: "ID"
time_col: "Time"
target: "Glucose"
drop_cols: ["Time"]

# Feature selection (paper)
fs_threshold: 0.005
rf_n_estimators: 1000
rf_random_state: 42

# XGBoost (paper)
base_params:
  max_depth: 6
  n_estimators: 100
  learning_rate: 0.1
  min_child_weight: 1.0
  subsample: 1.0
  colsample_bytree: 1.0
  reg_lambda: 1.0
  tree_method: "hist"
  n_jobs: 8
  random_state: 42

base_early_stopping_rounds: null
warm_start_frac: 0.0


